# Generated by Django 3.1.7 on 2021-03-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='level_of_difficulty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
